"/** @type {import('tailwindcss').Config} */\n"
"module.exports = {\n"
"  content: ['./**/*.{html,js,ts,jsx,tsx,py}'],\n"
"  theme: {\n"
"    extend: {\n"
"      colors: {\n"
"        cr: {\n"
"          bg:        '#0c0c0e',\n"
"          'bg-2':    '#111116',\n"
"          'bg-3':    '#16161d',\n"
"          panel:     '#13131a',\n"
"          'panel-2': '#19191f',\n"
"          'panel-3': '#1f1f28',\n"
"          brand:     '#c2410c',\n"
"          'brand-2': '#ea580c',\n"
"          'brand-3': '#9a3412',\n"
"          white:     '#f0f0f4',\n"
"          'white-2': '#b4b4c0',\n"
"          muted:     '#a1a1aa',\n"
"          'muted-2': '#78788a',\n"
"          red:       '#dc2626',\n"
"          yellow:    '#d97706',\n"
"          green:     '#16a34a',\n"
"          'green-dark': '#15803d',\n"
"        },\n"
"      },\n"
"      backgroundColor: {\n"
"        'cr-brand-soft':  'rgba(234,88,12,0.10)',\n"
"        'cr-green-soft':  'rgba(22,163,74,0.10)',\n"
"        'cr-red-soft':    'rgba(220,38,38,0.10)',\n"
"        'cr-yellow-soft': 'rgba(217,119,6,0.10)',\n"
"      },\n"
"      borderColor: {\n"
"        'cr-line':         'rgba(255,255,255,0.07)',\n"
"        'cr-line-strong':  'rgba(255,255,255,0.12)',\n"
"        'cr-line-3':       'rgba(255,255,255,0.18)',\n"
"        'cr-brand-line':   'rgba(234,88,12,0.30)',\n"
"        'cr-green-border': 'rgba(22,163,74,0.28)',\n"
"        'cr-switch':       'rgba(255,255,255,0.12)',\n"
"      },\n"
"      borderRadius: {\n"
"        'cr-sm': '6px',\n"
"        'cr':    '10px',\n"
"        'cr-lg': '14px',\n"
"      },\n"
"      fontFamily: {\n"
"        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '\"Segoe UI\"', 'sans-serif'],\n"
"        mono: ['ui-monospace', '\"SF Mono\"', 'Menlo', 'Consolas', 'monospace'],\n"
"      },\n"
"      boxShadow: {\n"
"        'cr-panel':   '0 4px 24px -6px rgba(0,0,0,0.5)',\n"
"        'cr-btn':     '0 4px 14px rgba(0,0,0,0.32)',\n"
"        'cr-glow-brand': '0 0 22px rgba(234,88,12,0.22)',\n"
"        'cr-glow-green': '0 0 14px rgba(22,163,74,0.28)',\n"
"        'cr-glow-red':   '0 0 12px rgba(220,38,38,0.28)',\n"
"        'cr-switch-inner': 'inset 0 1px 0 rgba(255,255,255,0.04), inset 0 -1px 0 rgba(0,0,0,0.28)',\n"
"      },\n"
"      keyframes: {\n"
"        crPanelDeploy: {\n"
"          from: { opacity: '0', transform: 'translateY(16px)' },\n"
"          to:   { opacity: '1', transform: 'translateY(0)' },\n"
"        },\n"
"        crScanSweep: {\n"
"          from: { transform: 'translateX(-120%)' },\n"
"          to:   { transform: 'translateX(120%)' },\n"
"        },\n"
"        crSwitchScan: {\n"
"          to: { transform: 'translateX(100%)' },\n"
"        },\n"
"        crStatusTick: {\n"
"          '0%, 100%': { opacity: '1' },\n"
"          '50%':      { opacity: '0.35' },\n"
"        },\n"
"        crToastIn: {\n"
"          from: { opacity: '0', transform: 'translateY(-5px) scale(0.97)' },\n"
"          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },\n"
"        },\n"
"        crCardPulse: {\n"
"          '0%, 100%': { boxShadow: 'none' },\n"
"          '50%':      { boxShadow: '0 0 22px rgba(234,88,12,0.22)' },\n"
"        },\n"
"        crVertScan: {\n"
"          '0%':   { top: '-4px', opacity: '1' },\n"
"          '100%': { top: '100%', opacity: '0.4' },\n"
"        },\n"
"        crRowReveal: {\n"
"          from: { opacity: '0', transform: 'translateY(6px)' },\n"
"          to:   { opacity: '1', transform: 'translateY(0)' },\n"
"        },\n"
"      },\n"
"      animation: {\n"
"        'cr-panel-deploy': 'crPanelDeploy 0.22s cubic-bezier(0.16,1,0.3,1)',\n"
"        'cr-scan-sweep':   'crScanSweep 0.9s linear infinite',\n"
"        'cr-switch-scan':  'crSwitchScan 0.75s linear infinite',\n"
"        'cr-status-tick':  'crStatusTick 2s infinite',\n"
"        'cr-toast-in':     'crToastIn 0.22s cubic-bezier(0.16,1,0.3,1) forwards',\n"
"        'cr-card-pulse':   'crCardPulse 1.1s ease-in-out infinite',\n"
"        'cr-vert-scan':    'crVertScan 0.85s linear infinite',\n"
"        'cr-row-reveal':   'crRowReveal 0.20s ease both',\n"
"      },\n"
"      transitionTimingFunction: {\n"
"        'cr-spring': 'cubic-bezier(0.2, 0.8, 0.2, 1)',\n"
"      },\n"
"      gridTemplateColumns: {\n"
"        'cr-shell':   'minmax(0,1fr) 320px',\n"
"        'cr-toolbar': 'minmax(0,1fr) auto auto auto',\n"
"        'cr-switch':  '1fr 1fr',\n"
"        'cr-stat':    '1fr 1fr',\n"
"        'cr-cheat':   '1fr auto',\n"
"      },\n"
"      maxWidth: {\n"
"        'cr-shell': '1540px',\n"
"      },\n"
"      zIndex: {\n"
"        'cr-bg':      '-3',\n"
"        'cr-grid':    '-2',\n"
"        'cr-circuit': '-1',\n"
"        'cr-toast':   '100000',\n"
"        'cr-trainer': '99999',\n"
"        'cr-modal':   '200',\n"
"      },\n"
"    },\n"
"  },\n"
"  plugins: [],\n"
"}\n"
